### ISSUE TITLE
Extraneous webpack stuff 

### ISSUE THREAD

**Issue by mkuipers** [prithvi16/rails-tailwind-esbuild-starter#1]
Any reason you've left all the webpacker stuff in here? Should be able to remove a lot of that, yeah?

**Comment by prithvi16** [comment]
Yes, I made this very quickly just to prototype when the Esbuild gem came out.  Rails 7 has changed a lot of stuff after I released this. They have added this in Rails generators. If you plan on using this boilerplate I can remove all the Webpack stuff.

**Comment by mkuipers** [comment]
No need. This is a helpful boilerplate for rails 6 with esbuild. I was just more curious if there was a reason it was left in.  Thank you. 

Max
